# .gitlab-ci.yml

stages:
  - build
  - test
  - docker_build
  - deploy

variables:
  GO_IMAGE: golang:1.19-alpine  # Docker образ для побудови Go додатку
  DOCKER_IMAGE: registry.gitlab.com/your-namespace/your-project/myapp  # замініть на реальний шлях до реєстру

build:
  stage: build
  image: $GO_IMAGE
  script:
    - apk add --no-cache git
    - go mod download
    - go build -o myapp .
  artifacts:
    paths:
      - myapp  # артефакт, який буде використовуватися на інших етапах

docker_build:
  stage: docker_build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA -f Dockerfile .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
  only:
    - main  # цей етап буде виконуватися лише для основної гілки

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying the app..."
  only:
    - main
